FROM nginx
COPY . /app
WORKDIR /app
ENV TZ="Asia/Shanghai"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN npm config set registry http://registry.npm.taobao.org
RUN npm install
EXPOSE 3000
CMD ["npm", "run" , "dev"]

